/**
 * Simple PDF generation utility for Theatre Shifts
 * Uses basic text formatting to create downloadable reports
 */

export interface ShiftData {
  show_name: string;
  role: string;
  date: string;
  time: string;
}

export interface VolunteerData {
  name: string;
  email: string | null;
}

export function generateShiftRemovalPDF(volunteer: VolunteerData, shifts: ShiftData[]): Uint8Array {
  const content = generatePDFContent(volunteer, shifts);
  
  // For a simple implementation, we'll return a plain text file
  // In production, you might want to use a library like jsPDF or puppeteer
  return new TextEncoder().encode(content);
}

function generatePDFContent(volunteer: VolunteerData, shifts: ShiftData[]): string {
  const currentDate = new Date().toLocaleDateString('en-AU', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  
  const currentTime = new Date().toLocaleTimeString('en-AU', {
    hour: '2-digit',
    minute: '2-digit'
  });

  return `THEATRE SHIFTS - VOLUNTEER REMOVAL REPORT
==========================================

Generated: ${currentDate} at ${currentTime}
Administrator: System Automated Process

VOLUNTEER INFORMATION
====================
Name: ${volunteer.name}
Email: ${volunteer.email || 'Not provided'}
Status: Login access disabled

REMOVED SHIFTS
==============
${shifts.length === 0 ? 'No future shifts were assigned to this volunteer.' : 
  shifts.map((shift, index) => `
${index + 1}. SHOW: ${shift.show_name}
   ROLE: ${shift.role}
   DATE: ${shift.date}
   TIME: ${shift.time}
   STATUS: Removed from assignment
`).join('')}

SUMMARY
=======
Total shifts removed: ${shifts.length}
Action taken: Volunteer login disabled, all shift assignments removed
Reason: Administrative action - login access revoked

IMPACT
======
${shifts.length > 0 ? 
  `The following ${shifts.length} shift${shifts.length > 1 ? 's' : ''} ${shifts.length > 1 ? 'are' : 'is'} now available for reassignment:
${shifts.map(shift => `- ${shift.show_name} (${shift.role}) on ${shift.date}`).join('\n')}

Please ensure these shifts are reassigned to other volunteers before the performance dates.` :
  'No shifts were affected by this action.'}

NEXT ACTIONS
============
1. Review the list of removed shifts above
2. Reassign shifts to other volunteers as needed
3. Update any related documentation or schedules
4. Notify relevant team members if required

This report was automatically generated by the Theatre Shifts Management System.
For questions about this action, please contact the system administrator.

Theatre Shifts Management System
Report Generated: ${new Date().toISOString()}
`;
}

export function getMimeType(): string {
  return "text/plain";
}

export function getFileExtension(): string {
  return "txt";
}

// In a production environment, you might want to use a proper PDF library
// such as jsPDF for client-side generation or Puppeteer for server-side generation
// For now, this provides a readable text-based report that can be easily downloaded
